#index:
#    path: /
#    controller: App\Controller\DefaultController::index
my_page:
    path: /RogachevaIrina
    controller: App\Controller\MyPageController::myPage

menu:
    path: /
    controller: App\Controller\PizzaController::getMenu

registration:
    path: /registration
    controller: App\Controller\PizzaController::registration

authorisation:
    path: /authorisation
    controller: App\Controller\PizzaController::authorisation

orders:
    path: /orders
    controller: App\Controller\PizzaController::getOrders

